### ISSUE TITLE
[BUG] (wrong environment)

### ISSUE THREAD

**Issue by ivanra48** [Help3D-Padova/Artillery_Marlin_2.0.9.3#1]
### Did you test the latest `bugfix-2.0.x` code?

Yes, and the problem still exists.

### Bug Description

platformio.ini

default_envs = mega2560  (wrong)

default_envs = Artillery_Ruby

### Version of Marlin Firmware

2.0.9.3

**Comment by Help3D-Padova** [comment]
![image](https://user-images.githubusercontent.com/76519178/152440297-0416b423-6b8c-4b4e-b95f-6193d10b92b9.png)

When compiling just select the right environment, there is no need to change from the platform.io
